### ISSUE TITLE
您好，能加个好友吗

### ISSUE THREAD

**Issue by shiyuleixia** [amusi/daily-paper-computer-vision#12]
QQ：360143263
我也再搞计算机视觉，目前主要是人脸识别、姿态迁移这些，PaddleGan、FOMM等等这些模型都研究过，有机会希望可以和兄弟交流下，谢谢

**Comment by ZhaoHang1991** [comment]
我已经没有继续搞计算机视觉了，抱歉！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: shiyuleixia ***@***.***&gt;
发送时间: 2021年9月17日 12:26
收件人: amusi/daily-paper-computer-vision ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[amusi/daily-paper-computer-vision] 您好，能加个好友吗 (#12)





 
QQ：360143263
 我也再搞计算机视觉，目前主要是人脸识别、姿态迁移这些，PaddleGan、FOMM等等这些模型都研究过，有机会希望可以和兄弟交流下，谢谢
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shnulailai** [comment]
你好，为什么没有继续搞计算机视觉了呢？兄弟还有什么更好的出路吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amusi/daily-paper-computer-vision"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月17日(星期五) 中午12:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [amusi/daily-paper-computer-vision] 您好，能加个好友吗 (#12)





 我已经没有继续搞计算机视觉了，抱歉！ 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: shiyuleixia ***@***.***&amp;gt; 
 发送时间: 2021年9月17日 12:26 
 收件人: amusi/daily-paper-computer-vision ***@***.***&amp;gt; 
 抄送: Subscribed ***@***.***&amp;gt; 
 主题: 回复：[amusi/daily-paper-computer-vision] 您好，能加个好友吗 (#12) 
 
 
 
 
 
   
 QQ：360143263 
  我也再搞计算机视觉，目前主要是人脸识别、姿态迁移这些，PaddleGan、FOMM等等这些模型都研究过，有机会希望可以和兄弟交流下，谢谢 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shnulailai** [comment]
没有，已经工作了，也是去年才转到这行的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amusi/daily-paper-computer-vision"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月28日(星期二) 中午11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amusi/daily-paper-computer-vision] 您好，能加个好友吗 (#12)





 你还在高校么？ 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: shnulailai ***@***.***&amp;gt; 
 发送时间: 2021年9月27日 18:32 
 收件人: amusi/daily-paper-computer-vision ***@***.***&amp;gt; 
 抄送: ZhaoHang1991 ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 主题: 回复：[amusi/daily-paper-computer-vision] 您好，能加个好友吗 (#12) 
 
 
 
 
 
  你好，为什么没有继续搞计算机视觉了呢？兄弟还有什么更好的出路吗  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "amusi/daily-paper-computer-vision"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年9月17日(星期五) 中午12:29  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [amusi/daily-paper-computer-vision] 您好，能加个好友吗 (#12)  
   
   
   
   
   
   我已经没有继续搞计算机视觉了，抱歉！   
     
     
     
   发自我的iPhone   
     
     
   ------------------ 原始邮件 ------------------   
   发件人: shiyuleixia ***@***.***&amp;amp;amp;gt;   
   发送时间: 2021年9月17日 12:26   
   收件人: amusi/daily-paper-computer-vision ***@***.***&amp;amp;amp;gt;   
   抄送: Subscribed ***@***.***&amp;amp;amp;gt;   
   主题: 回复：[amusi/daily-paper-computer-vision] 您好，能加个好友吗 (#12)   
     
     
     
     
     
       
   QQ：360143263   
    我也再搞计算机视觉，目前主要是人脸识别、姿态迁移这些，PaddleGan、FOMM等等这些模型都研究过，有机会希望可以和兄弟交流下，谢谢   
       
   —   
   You are receiving this because you are subscribed to this thread.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you are subscribed to this thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shnulailai** [comment]
您的来信我已经收到了！
